version: '3.8'

services:

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    


  api:
    build:
      dockerfile: dockerfile
      context: ./
    depends_on:
      - redis


  client:
    build: 
      dockerfile: dockerfile
      context: ./client
    ports:
      - '3000:80'
    depends_on:
      - api



